/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vues;
import controleur.CtrlAbstrait;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author btssio
 */
public class VueRapportsVisite extends VueAbstraite {

    /**
     * Creates new form rapports_visite
     */
    public VueRapportsVisite(CtrlAbstrait ctrl) {
        super(ctrl);
        initComponents();
        this.setLocation(500, 200);
    }

    public JButton getjButtonDetails() {
        return jButtonDetails;
    }

    public void setjButtonDetails(JButton jButtonDetails) {
        this.jButtonDetails = jButtonDetails;
    }

    public JButton getjButtonFermer() {
        return jButtonFermer;
    }

    public void setjButtonFermer(JButton jButtonFermer) {
        this.jButtonFermer = jButtonFermer;
    }

    public JButton getjButtonNouv() {
        return jButtonNouv;
    }

    public void setjButtonNouv(JButton jButtonNouv) {
        this.jButtonNouv = jButtonNouv;
    }

    public JButton getjButtonprec() {
        return jButtonPrec;
    }

    public void setjButtonprec(JButton jButtonprec) {
        this.jButtonPrec = jButtonprec;
    }

    public JButton getjButtonSuiv() {
        return jButtonSuiv;
    }

    public void setjButtonSuiv(JButton jButtonSuiv) {
        this.jButtonSuiv = jButtonSuiv;
    }

    public JComboBox getjComboBoxpraticien() {
        return jComboBoxPraticien;
    }

    public void setjComboBoxpraticien(JComboBox jComboBoxpraticien) {
        this.jComboBoxPraticien = jComboBoxpraticien;
    }

    public JLabel getjLabelBilan() {
        return jLabelBilan;
    }

    public void setjLabelBilan(JLabel jLabelBilan) {
        this.jLabelBilan = jLabelBilan;
    }

    public JLabel getjLabelDate() {
        return jLabelDate;
    }

    public void setjLabelDate(JLabel jLabelDate) {
        this.jLabelDate = jLabelDate;
    }

    public JLabel getjLabelMotif() {
        return jLabelMotif;
    }

    public void setjLabelMotif(JLabel jLabelMotif) {
        this.jLabelMotif = jLabelMotif;
    }

    public JLabel getjLabelNum() {
        return jLabelNum;
    }

    public void setjLabelNum(JLabel jLabelNum) {
        this.jLabelNum = jLabelNum;
    }

    public JLabel getjLabelOffre() {
        return jLabelOffre;
    }

    public void setjLabelOffre(JLabel jLabelOffre) {
        this.jLabelOffre = jLabelOffre;
    }

    public JLabel getjLabelPraticien() {
        return jLabelPraticien;
    }

    public void setjLabelPraticien(JLabel jLabelPraticien) {
        this.jLabelPraticien = jLabelPraticien;
    }

    public JLabel getjLabeltitre() {
        return jLabelTitre;
    }

    public void setjLabeltitre(JLabel jLabeltitre) {
        this.jLabelTitre = jLabeltitre;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTableOffre() {
        return jTableOffre;
    }

    public void setjTableOffre(JTable jTableOffre) {
        this.jTableOffre = jTableOffre;
    }

    public JTextArea getjTextAreabilan() {
        return jTextAreabilan;
    }

    public void setjTextAreabilan(JTextArea jTextAreabilan) {
        this.jTextAreabilan = jTextAreabilan;
    }

    public JTextField getjTextFieldDate() {
        return jTextFieldDate;
    }

    public void setjTextFieldDate(JTextField jTextFieldDate) {
        this.jTextFieldDate = jTextFieldDate;
    }

    public JTextField getjTextFieldMotif() {
        return jTextFieldMotif;
    }

    public void setjTextFieldMotif(JTextField jTextFieldMotif) {
        this.jTextFieldMotif = jTextFieldMotif;
    }

    public JTextField getjTextFieldNum() {
        return jTextFieldNum;
    }

    public void setjTextFieldNum(JTextField jTextFieldNum) {
        this.jTextFieldNum = jTextFieldNum;
    }

    public JButton getjButtonSauvegarder() {
        return jButtonSauvegarder;
    }

    public void setjButtonSauvegarder(JButton jButtonSauvegarder) {
        this.jButtonSauvegarder = jButtonSauvegarder;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        jLabelNum = new javax.swing.JLabel();
        jLabelPraticien = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelMotif = new javax.swing.JLabel();
        jLabelBilan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreabilan = new javax.swing.JTextArea();
        jTextFieldMotif = new javax.swing.JTextField();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldNum = new javax.swing.JTextField();
        jComboBoxPraticien = new javax.swing.JComboBox();
        jButtonDetails = new javax.swing.JButton();
        jButtonPrec = new javax.swing.JButton();
        jButtonSuiv = new javax.swing.JButton();
        jButtonNouv = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOffre = new javax.swing.JTable();
        jLabelOffre = new javax.swing.JLabel();
        jButtonSauvegarder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitre.setText("RAPPORTS DE VISITE");

        jLabelNum.setText("Numéro Rapport");

        jLabelPraticien.setText("Praticien");

        jLabelDate.setText("Date Rapport");

        jLabelMotif.setText("Motif Visite");

        jLabelBilan.setText("BILAN");

        jTextAreabilan.setColumns(20);
        jTextAreabilan.setRows(5);
        jScrollPane1.setViewportView(jTextAreabilan);

        jTextFieldNum.setEditable(false);

        jComboBoxPraticien.setEditable(true);
        jComboBoxPraticien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonDetails.setText("Détails");

        jButtonPrec.setText("Précédent");

        jButtonSuiv.setText("Suivant");

        jButtonNouv.setText("Nouveau");

        jButtonFermer.setText("Fermer");

        jTableOffre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Médicament", "Nb. Echantillons"
            }
        ));
        jScrollPane2.setViewportView(jTableOffre);

        jLabelOffre.setText("Offre d'échantillons");

        jButtonSauvegarder.setText("Sauvegarder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabelTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPrec)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonSuiv)
                                .addGap(35, 35, 35)
                                .addComponent(jButtonNouv)
                                .addGap(20, 20, 20)
                                .addComponent(jButtonSauvegarder))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelPraticien)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelNum)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxPraticien, 0, 198, Short.MAX_VALUE)
                                                .addComponent(jTextFieldNum)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabelDate)
                                                    .addGap(35, 35, 35))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabelMotif)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                                .addComponent(jTextFieldMotif))))
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonDetails))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelBilan)
                                    .addGap(86, 86, 86)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelOffre)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonFermer)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNum)
                            .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonDetails))
                            .addComponent(jLabelPraticien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDate)
                            .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMotif, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabelBilan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelOffre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrec)
                    .addComponent(jButtonSuiv)
                    .addComponent(jButtonNouv)
                    .addComponent(jButtonFermer)
                    .addComponent(jButtonSauvegarder))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetails;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonNouv;
    private javax.swing.JButton jButtonPrec;
    private javax.swing.JButton jButtonSauvegarder;
    private javax.swing.JButton jButtonSuiv;
    private javax.swing.JComboBox jComboBoxPraticien;
    private javax.swing.JLabel jLabelBilan;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelMotif;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelOffre;
    private javax.swing.JLabel jLabelPraticien;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableOffre;
    private javax.swing.JTextArea jTextAreabilan;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldMotif;
    private javax.swing.JTextField jTextFieldNum;
    // End of variables declaration//GEN-END:variables
}
